# Generated by Django 3.0.1 on 2020-01-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customers registered under HousingSolutions'},
        ),
    ]
