# Generated by Django 3.0.2 on 2020-01-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200101_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers registered under HousingSolutions'},
        ),
    ]
