# Generated by Django 3.0.2 on 2020-01-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking'),
        ('customer', '0005_customer_booked_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='booked_property',
        ),
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.OneToOneField(help_text='Booking', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
        ),
    ]
