# Generated by Django 3.0.2 on 2020-01-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking'),
        ('customer', '0008_auto_20200114_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Booking'),
        ),
    ]
