# Generated by Django 3.0.2 on 2020-01-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200114_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='booking',
        ),
    ]
