# Generated by Django 3.0.1 on 2019-12-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Image url')),
                ('alt', models.CharField(max_length=20, verbose_name='Image description ')),
            ],
        ),
    ]
