# Generated by Django 3.0.1 on 2019-12-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Eindhoven', help_text='City', max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Netherlands', help_text='Country', max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(help_text='Locality', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Street', max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='5611KT', help_text='Postal code', max_length=12),
        ),
    ]
