# Generated by Django 3.0.1 on 2019-12-31 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20191231_1512'),
        ('common', '0003_image_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='property',
            field=models.ForeignKey(help_text='Property Images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='property.Property'),
        ),
    ]
