# Generated by Django 3.0.1 on 2020-01-01 11:33

import common.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20191231_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Property Image'},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(countries=common.models.EUCountries, default='NL', help_text='Countries in EU Union', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=20, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
