# Generated by Django 3.0.1 on 2020-01-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200101_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='locality',
        ),
    ]
