# Generated by Django 3.0.1 on 2020-01-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('property', '0008_auto_20200101_1342'),
        ('common', '0006_remove_address_locality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Property Address'},
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.OneToOneField(help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='name',
            name='customer',
            field=models.OneToOneField(help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='property',
            field=models.OneToOneField(help_text='Property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='property.Property'),
        ),
    ]
