# Generated by Django 3.0.2 on 2020-01-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_name_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address'},
        ),
    ]
