# Generated by Django 3.0.1 on 2020-01-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20200101_1827'),
        ('property', '0008_auto_20200101_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='customer.Customer')),
                ('property', models.ForeignKey(help_text='Property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='property.Property')),
            ],
            options={
                'verbose_name': 'Booking',
            },
        ),
    ]
