# Generated by Django 3.0.2 on 2020-01-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200102_1400'),
        ('property', '0008_auto_20200101_1342'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Bookings for properties'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='property',
            field=models.OneToOneField(help_text='Property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='property.Property'),
        ),
    ]
