# Generated by Django 3.0.2 on 2020-01-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200102_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
