# Generated by Django 3.0.2 on 2020-01-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_customer_booking'),
        ('booking', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer'),
        ),
    ]
