# Generated by Django 3.0.1 on 2019-12-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20191231_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='catergory',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('room', 'Room'), ('bungalow', 'bungalow'), ('house', 'House')], default='apartment', help_text='Property Type', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='interior',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-furnished'), ('furnished', 'furnished')], default='unfurnished', help_text='Property Type', max_length=20),
        ),
    ]
