# Generated by Django 3.0.1 on 2019-12-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20191231_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='interior',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-furnished'), ('furnished', 'Furnished')], default='unfurnished', help_text='Property Interior', max_length=20),
        ),
    ]
