# Generated by Django 3.0.1 on 2019-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20191231_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprice',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Property deposit (in €)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='propertyprice',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Property rent (in €)', max_digits=6),
        ),
    ]
