# Generated by Django 3.0.1 on 2020-01-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20191231_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprice',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Property deposit (in €)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='propertyprice',
            name='property',
            field=models.OneToOneField(default=None, help_text='Property', on_delete=django.db.models.deletion.CASCADE, related_name='property_price', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='propertyprice',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Property rent (in €)', max_digits=6),
        ),
    ]
