# Generated by Django 3.0.1 on 2020-01-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200101_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties under HousingSolutions'},
        ),
    ]
