# Generated by Django 3.0.2 on 2020-01-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200101_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='catergory',
            new_name='category',
        ),
    ]
