# Generated by Django 3.0.4 on 2020-03-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200105_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default='51.4416', help_text='Property Address - latitude', max_digits=9),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='5.4697', help_text='Property Address - longitude', max_digits=9),
        ),
    ]
